### ISSUE TITLE
logfile error if including trailing slash in runfolder path

### ISSUE THREAD

**Issue by andyb3** [moka-guys/workstation_housekeeping#11]
If you include the trailing slash when specifying the runfolder, the `os.path.basename` command in `log_setup()` returns and empty string resulting in the logfile being written to a hidden file called `.log`

**Comment by aledj2** [comment]
doesn't appear to be an issue any more?

**Comment by aledj2** [comment]
is still an issue - change line 44 
logfile_name = "".join([os.path.basename(args.runfolder), ".log"])
to
logfile_name = "".join([os.path.basename(args.runfolder.strip("/")), ".log"])
